export default {
  MUTATIONS_CART_ADDTOCART: 'MUTATIONS_CART_ADDTOCART',
  MUTATIONS_SHOW_CART: 'MUTATIONS_SHOW_CART',
  MUTATIONS_REMOVE_CART: 'MUTATIONS_REMOVE_CART',
  MUTATIONS_REMOVE_PRODUCTCART: 'MUTATIONS_REMOVE_PRODUCTCART',
  MUTATIONS_LOAD_CART: 'MUTATIONS_LOAD_CART',
  MUTATIONS_PLUS_ITEMCART: 'MUTATIONS_PLUS_ITEMCART',
  MUTATIONS_MINUS_ITEMCART: 'MUTATIONS_MINUS_ITEMCART',
}
