export default {
  MUTATIONS_CART_ADDTOCART: 'MUTATIONS_CART_ADDTOCART',
  MUTATIONS_REMOVE_PRODUCTCART: 'MUTATIONS_REMOVE_PRODUCTCART',
  MUTATIONS_LOAD_CART: 'MUTATIONS_LOAD_CART',
  ACTION_CART_ADDTOCART: 'user/cart/addProdcutToCart',
  ACTION_REMOVE_PRODUCTCART: 'user/cart/removeProductCart',
  ACTION_LOAD_CART: 'user/cart/render',
}
