export default {
  MUTATIONS_CART_ADDTOCART_USER: 'MUTATIONS_CART_ADDTOCART_USER',
  MUTATIONS_SHOW_CART_USER: 'MUTATIONS_SHOW_CART_USER',
  MUTATIONS_UPDATE_CART_USER: 'MUTATIONS_UPDATE_CART_USER',
  MUTATIONS_REMOVE_CART_USER: 'MUTATIONS_REMOVE_CART_USER',
  MUTATIONS_REMOVE_PRODUCTCART_USER: 'MUTATIONS_REMOVE_PRODUCTCART_USER',
  MUTATIONS_LOAD_CART_USER: 'MUTATIONS_LOAD_CART__USER',
  MUTATIONS_PLUS_ITEMCART_USER: 'MUTATIONS_PLUS_ITEMCART_USER',
  MUTATIONS_MINUS_ITEMCART_USER: 'MUTATIONS_MINUS_ITEMCART_USER',

  MUTATIONS_CART_ADDTOCART: 'MUTATIONS_CART_ADDTOCART',
  MUTATIONS_REMOVE_PRODUCTCART: 'MUTATIONS_REMOVE_PRODUCTCART',
  MUTATIONS_LOAD_CART: 'MUTATIONS_LOAD_CART',
  MUTATIONS_PLUS_ITEMCART: 'MUTATIONS_PLUS_ITEMCART',
  MUTATIONS_MINUS_ITEMCART: 'MUTATIONS_MINUS_ITEMCART',
}
