export default () => ({
  MUTATION_ADMIN_CATEGORY_INIT: 'MUTATION_ADMIN_CATEGORY_INIT',
  MUTATION_ADMIN_ADD_CONTENT: 'MUTATION_ADMIN_ADD_CONTENT',
  MUTATION_ADMIN_UPDATE_CONTENT: 'MUTATION_ADMIN_UPDATE_CONTENT',
  MUTATION_ADMIN_DELETE_CONTENT: 'MUTATION_ADMIN_UPDATE_CONTENT',

  ACTION_ADMIN_CATEGORY_INIT: 'admin/category/init',
})
