export default {
  MUTATIONS_CHECKOUT_CHECKOUT: 'MUTATIONS_CHECKOUT_CHECKOUT',
  MUTATIONS_CHECKOUT_SETPRODUCT: 'MUTATIONS_CHECKOUT_SETPRODUCT',
  MUTATIONS_REMOVE_PRODUCT_CHECKOUT: 'MUTATIONS_REMOVE_PRODUCT_CHECKOUT',
}
