export default {
  MUTATIONS_INVOICE_CREATE: 'MUTATIONS_INVOICE_CREATE',
  MUTATIONS_INVOICE_GET: 'MUTATIONS_INVOICE_GET',
  MUTATION_INVOICE_NOT: 'MUTATION_INVOICE_NOT',
  MUTATION_INVOICE_ACCURACY: 'MUTATION_INVOICE_ACCURACY',
  MUTATION_INVOICE_TRANSPORT: 'MUTATION_INVOICE_TRANSPORT',
  MUTATION_INVOICE_COMPLETE: 'MUTATION_INVOICE_COMPLETE',
  MUTATION_INVOICE_CANCEL: 'MUTATION_INVOICE_CANCEL',
}
